
export const AUTH_CHANGE = 'AUTH_CHANGE'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS'
export const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE'

export const PROJECT_CREATE = 'PROJECT_CREATE'
export const PROJECT_CREATE_REQUEST = 'PROJECT_CREATE_REQUEST'
export const PROJECT_CREATE_SUCCESS = 'PROJECT_CREATE_SUCCESS'
export const PROJECT_CREATE_FAILURE = 'PROJECT_CREATE_FAILURE'

export const PROJECTS_GET = 'PROJECTS_GET'
export const PROJECTS_GET_REQUEST = 'PROJECTS_GET_REQUEST'
export const PROJECTS_GET_SUCCESS = 'PROJECTS_GET_SUCCESS'
export const PROJECTS_GET_FAILURE = 'PROJECTS_GET_FAILURE'
